name: Run Employer Branding Aggregator

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-aggregator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run aggregator script
      run: |
        python -v employer_branding_aggregator.py
        if [ $? -ne 0 ]; then
          echo "Script failed"
          exit 1
        fi
    
    - name: Debug information
      if: failure()
      run: |
        pwd
        ls -la
        git status
        cat multilingual_employer_branding_updates.txt || echo "Output file not found"
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions-bot@users.noreply.github.com'
    
    - name: Commit and push if changes
      run: |
        git add .
        git commit -m "Update employer branding aggregation" || echo "No changes to commit"
        git push || echo "No changes to push"
